version: '3'

services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:5.0.1-alpine
    command: redis-server
    volumes:
      - ./tmp/redis:/data
